Repository StretenskiyDanila/recreation-assistant, pull requests merged in 2023-07, with the labels that each got.

#5 Создание пустого бота, подключение к Spring Application
  pom.xml
  src/main/java/ru/recreation/recreationassistant/RecreationAssistantApplication.java
  src/main/java/ru/recreation/recreationassistant/ServletInitializer.java
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/configurations/ApplicationConfiguration.java
  src/main/java/ru/recreation/recreationassistant/configurations/BotConfig.java
  src/main/java/ru/recreation/recreationassistant/configurations/Initializer.java
  src/main/java/ru/recreation/recreationassistant/utils/TelegramChatUtils.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/config.properties
Labels: enhancement

#17 Создание сервиса рекомендаций рецептов еды.
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/entity/User.java
  src/main/java/ru/recreation/recreationassistant/models/Recipe.java
  src/main/java/ru/recreation/recreationassistant/models/RecipeHits.java
  src/main/java/ru/recreation/recreationassistant/models/RecipeRecommendation.java
  src/main/java/ru/recreation/recreationassistant/services/RecipeRecommendationsService.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipeRecommendationsServiceImpl.java
  src/main/resources/config.properties
Labels: enhancement

#23 Task#4 сервер поиска места
  pom.xml
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/models/City.java
  src/main/java/ru/recreation/recreationassistant/models/FactWeather.java
  src/main/java/ru/recreation/recreationassistant/models/Forecast.java
  src/main/java/ru/recreation/recreationassistant/models/WeatherInCity.java
  src/main/java/ru/recreation/recreationassistant/services/RecipientCoordinatesCity.java
  src/main/java/ru/recreation/recreationassistant/services/WeatherHelperService.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipientCoordinatesCityImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/SearchEventServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/WeatherHelperServiceImpl.java
  src/main/resources/config.properties
Labels: enhancement

#24 Объединил сервис еды и бота. Починил миграции и базу данных.
  pom.xml
  src/main/java/ru/recreation/recreationassistant/RecreationAssistantApplication.java
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/models/Recipe.java
  src/main/java/ru/recreation/recreationassistant/services/TranslationService.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipeRecommendationsServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/TranslationServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/utils/TypeOfDishesButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/TypeOfHealthButtons.java
  src/main/resources/application.properties
  src/main/resources/application.yaml
  src/main/resources/db/migration/V1__init_users_table.sql
  src/main/resources/db/migration/V2__init_health_labels_table.sql
  src/main/resources/db/migration/V3__init_meal_type_table.sql
  src/main/resources/db/migration/V4__init_dish_type_table.sql
  src/main/resources/db/migration/V5__init_cuisine_type_table.sql
  src/main/resources/db/migration/V6__insert_tables.sql
  src/test/java/ru/recreation/recreationassistant/RecreationAssistantApplicationTests.java
Labels: bug, enhancement

#26 1) Исправил ошибку с городом Нижний-Новгород
  pom.xml
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/services/RecipientCoordinatesCity.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipientCoordinatesCityImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/SearchEventServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/TranslationServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/utils/CityButtons.java
Labels: bug

#28 Task#27
  pom.xml
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/models/Event.java
  src/main/java/ru/recreation/recreationassistant/utils/StartButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/StationarySurveyStreet.java
  src/main/java/ru/recreation/recreationassistant/utils/TypeOfHealthButtons.java
Labels: bug

#32 Убрал хардкод апи ключей погоды
  src/main/java/ru/recreation/recreationassistant/configurations/WeatherApiConfig.java
  src/main/java/ru/recreation/recreationassistant/services/impl/WeatherHelperServiceImpl.java
  src/main/resources/config.properties
Labels: bug

#35 Логирование
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipeRecommendationsServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipientCoordinatesCityImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/SearchEventServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/WeatherHelperServiceImpl.java
Labels: invalid

#37 Добавлен ввод запроса пользователя в сервис еды.
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/services/TranslationService.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipeRecommendationsServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/TranslationServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/utils/ListUtils.java
  src/main/resources/config.properties
Labels: enhancement

#51 Поправил классы с аннотациями Lombok
  src/main/java/ru/recreation/recreationassistant/entity/Cuisine.java
  src/main/java/ru/recreation/recreationassistant/entity/Dish.java
  src/main/java/ru/recreation/recreationassistant/entity/Health.java
  src/main/java/ru/recreation/recreationassistant/entity/Meal.java
  src/main/java/ru/recreation/recreationassistant/entity/User.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipeRecommendationsServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/UserServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/WeatherHelperServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/utils/BotButtons.java
Labels: enhancement

#53 Поправил поля в models:
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/models/City.java
  src/main/java/ru/recreation/recreationassistant/models/Event.java
  src/main/java/ru/recreation/recreationassistant/models/Exhibition.java
  src/main/java/ru/recreation/recreationassistant/models/FactWeather.java
  src/main/java/ru/recreation/recreationassistant/models/Recipe.java
  src/main/java/ru/recreation/recreationassistant/models/RecipeHits.java
  src/main/java/ru/recreation/recreationassistant/models/RecipeRecommendation.java
  src/main/java/ru/recreation/recreationassistant/models/WeatherInCity.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipeRecommendationsServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/SearchEventServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/WeatherHelperServiceImpl.java
Labels: enhancement

#55 Во всех репозиториях и UserService методы теперь возвращают Optional.
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/exceptions/UserNotFoundException.java
  src/main/java/ru/recreation/recreationassistant/repositories/CuisineRepository.java
  src/main/java/ru/recreation/recreationassistant/repositories/DishRepository.java
  src/main/java/ru/recreation/recreationassistant/repositories/HealthRepository.java
  src/main/java/ru/recreation/recreationassistant/repositories/MealRepository.java
  src/main/java/ru/recreation/recreationassistant/services/UserService.java
  src/main/java/ru/recreation/recreationassistant/services/impl/UserServiceImpl.java
Labels: bug

#56 Убрал аннотацию @`Data
  src/main/java/ru/recreation/recreationassistant/TelegramBot.java
  src/main/java/ru/recreation/recreationassistant/entity/Cuisine.java
  src/main/java/ru/recreation/recreationassistant/entity/Dish.java
  src/main/java/ru/recreation/recreationassistant/entity/Health.java
  src/main/java/ru/recreation/recreationassistant/entity/Meal.java
  src/main/java/ru/recreation/recreationassistant/entity/User.java
  src/main/java/ru/recreation/recreationassistant/models/City.java
  src/main/java/ru/recreation/recreationassistant/models/Event.java
  src/main/java/ru/recreation/recreationassistant/models/Exhibition.java
  src/main/java/ru/recreation/recreationassistant/models/FactWeather.java
  src/main/java/ru/recreation/recreationassistant/models/Recipe.java
  src/main/java/ru/recreation/recreationassistant/models/RecipeHits.java
  src/main/java/ru/recreation/recreationassistant/models/RecipeRecommendation.java
  src/main/java/ru/recreation/recreationassistant/models/WeatherInCity.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipeRecommendationsServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RecipientCoordinatesCityImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/RestTemplateWork.java
  src/main/java/ru/recreation/recreationassistant/services/impl/SearchEventServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/TranslationServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/UserServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/services/impl/WeatherHelperServiceImpl.java
  src/main/java/ru/recreation/recreationassistant/utils/BotButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/ButtonInfo.java
  src/main/java/ru/recreation/recreationassistant/utils/CityButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/CountryKitchenButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/EventButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/ListUtils.java
  src/main/java/ru/recreation/recreationassistant/utils/StartButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/TypeOfDishesButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/TypeOfHealthButtons.java
  src/main/java/ru/recreation/recreationassistant/utils/TypeOfMealButtons.java
Labels: bug

#58 Json recommendation
  src/main/java/ru/recreation/recreationassistant/models/Recommendation.java
  src/main/java/ru/recreation/recreationassistant/services/impl/WeatherHelperServiceImpl.java
  src/main/resources/Recommendation.json
Labels: enhancement
